# Generated by Django 6.0.1 on 2026-01-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants_added_time_alter_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants_added_time',
        ),
    ]
