# Generated by Django 6.0.1 on 2026-01-26 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_participants_added_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_room', to=settings.AUTH_USER_MODEL)),
                ('user_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to='base.room')),
            ],
        ),
    ]
