# Generated by Django 6.0.1 on 2026-01-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
