# Generated by Django 6.0.1 on 2026-02-10 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_chatroom_chatmessage_groupinvite_messagereadstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_rooms', to='base.chatroom'),
        ),
    ]
