# Generated by Django 6.0.1 on 2026-02-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagereadstatus',
            name='unique_message_user',
        ),
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
