# Generated by Django 6.0.1 on 2026-02-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_messagereadstatus_unique_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
