# Generated by Django 6.0.1 on 2026-02-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_roommember_last_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='chatroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_rooms', to='base.chatroom'),
        ),
    ]
