# Generated by Django 6.0.1 on 2026-03-01 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='last_read',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
