# Generated by Django 6.0.1 on 2026-03-01 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_roommember_last_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='last_read',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
